import socket

# s , "=", socket.socket(socket.AF_INET, socket.SOCK_STREAM, 0)
# # s.setsockopt(0, 2, 1)
# s.getsockopt(0, 2)
# s.accept()

# Socket Type constants
# print("alias", "SOCK_STREAM", "=", socket.SOCK_STREAM)
# print("alias", "SOCK_DGRAM" , "=", socket.SOCK_DGRAM)
# print("alias", "SOCK_RAW" , "=", socket.SOCK_RAW)
# print("alias", "SOCK_RDM" , "=", socket.SOCK_RDM)
# print("alias", "SOCK_SEQPACKET" , "=", socket.SOCK_SEQPACKET)
# print("alias", "SOCK_DCCP" , "=", socket.SOCK_DCCP)
# print("alias", "SOCK_PACKET" , "=", socket.SOCK_PACKET)
# print("alias", "SOCK_CLOEXEC" , "=", socket.SOCK_CLOEXEC)
# print("alias", "SOCK_NONBLOCK" , "=", socket.SOCK_NONBLOCK)

# Address Information
# print("alias", "AI_PASSIVE" , "=", socket.AI_PASSIVE)
# print("alias", "AI_CANONNAME" , "=", socket.AI_CANONNAME)
# print("alias", "AI_NUMERICHOST" , "=", socket.AI_NUMERICHOST)
# print("alias", "AI_V4MAPPED" , "=", socket.AI_V4MAPPED)
# print("alias", "AI_ALL" , "=", socket.AI_ALL)
# print("alias", "AI_ADDRCONFIG" , "=", socket.AI_ADDRCONFIG)
# print("alias", "AI_IDN" , "=", socket.AI_IDN)

# print("alias", "INET_ADDRSTRLEN" , "=", socket.INET_ADDRSTRLEN)
# print("alias", "INET6_ADDRSTRLEN" , "=", socket.INET6_ADDRSTRLEN)

# print("alias", "SHUT_RD" , "=", socket.SHUT_RD)
# print("alias", "SHUT_WR" , "=", socket.SHUT_WR)
# print("alias", "SHUT_RDWR" , "=", socket.SHUT_RDWR)

# print("alias", "SOL_SOCKET" , "=", socket.SOL_SOCKET)

# Socket Options
print("alias", "SO_DEBUG" , "=", socket.SO_DEBUG)
print("alias", "SO_REUSEADDR" , "=", socket.SO_REUSEADDR)
print("alias", "SO_TYPE" , "=", socket.SO_TYPE)
print("alias", "SO_ERROR" , "=", socket.SO_ERROR)
print("alias", "SO_DONTROUTE" , "=", socket.SO_DONTROUTE)
print("alias", "SO_BROADCAST" , "=", socket.SO_BROADCAST)
print("alias", "SO_SNDBUF" , "=", socket.SO_SNDBUF)
print("alias", "SO_RCVBUF" , "=", socket.SO_RCVBUF)
print("alias", "SO_KEEPALIVE" , "=", socket.SO_KEEPALIVE)
print("alias", "SO_OOBINLINE" , "=",  socket.SO_OOBINLINE)
# print("alias", "SO_NO_CHECK" , "=",  socket.SO_NO_CHECK)
# print("alias", "SO_PRIORITY" , "=",  socket.SO_PRIORITY)
print("alias", "SO_LINGER" , "=",  socket.SO_LINGER)
# print("alias", "SO_BSDCOMPAT" , "=",  socket.SO_BSDCOMPAT)
print("alias", "SO_REUSEPORT" , "=",  socket.SO_REUSEPORT)
# print("alias", "SO_PASSCRED" , "=",  socket.SO_PASSCRED)
# print("alias", "SO_PEERCRED" , "=",  socket.SO_PEERCRED)
print("alias", "SO_RCVLOWAT" , "=",  socket.SO_RCVLOWAT)
print("alias", "SO_SNDLOWAT" , "=",  socket.SO_SNDLOWAT)
print("alias", "SO_RCVTIMEO" , "=",  socket.SO_RCVTIMEO)
print("alias", "SO_SNDTIMEO" , "=", socket.SO_SNDTIMEO)
print("alias", "SO_RCVTIMEO_OLD" , "=", socket.SO_RCVTIMEO)
print("alias", "SO_SNDTIMEO_OLD" , "=", socket.SO_SNDTIMEO)
# print("alias", "SO_SECURITY_AUTHENTICATION" , "=", socket.SO_SECURITY_AUTHENTICATION)
# print("alias", "SO_SECURITY_ENCRYPTION_TRANSPORT" , "=", socket.SO_SECURITY_ENCRYPTION_TRANSPORT)
# print("alias", "SO_SECURITY_ENCRYPTION_NETWORK" , "=", socket.SO_SECURITY_ENCRYPTION_NETWORK)
# print("alias", "SO_BINDTODEVICE" , "=", socket.SO_BINDTODEVICE)
# print("alias", "SO_ATTACH_FILTER" , "=", socket.SO_ATTACH_FILTER)
# print("alias", "SO_DETACH_FILTER" , "=", socket.SO_DETACH_FILTER)
# print("alias", "AF_RDS" , "=", socket.AF_RDS)
print("alias", "SO_ACCEPTCONN" , "=", socket.SO_ACCEPTCONN)